export type Variety = {
  id: string;
  name: string;
  origin: string;
  grade: string;
  moisture: string;
  color: string;
  packing: string[];
  minOrder: string;
  description: string;
  specs: { label: string; value: string }[];
};

export type Product = {
  id: string;
  name: string;
  category: "spices" | "commodities";
  emoji: string;
  tagline: string;
  description: string;
  heroColor: string;
  hsCode: string;
  varieties: Variety[];
  certifications: string[];
  originRegions: string[];
};

export const products: Product[] = [
  {
    id: "turmeric",
    name: "Turmeric",
    category: "spices",
    emoji: "🟡",
    hsCode: "HS 0910.30",
    tagline: "Erode, Salem, Assam & Nizamabad origin — Curcumin 3–5%",
    description: "Single-origin Indian turmeric with curcumin content of 3–5%. Available as whole finger, sliced & steam-sterilised powder. 18–24 month vacuum-packed shelf life.",
    heroColor: "#E8A020",
    certifications: ["FSSAI", "Organic on request"],
    originRegions: ["Erode", "Salem", "Assam", "Nizamabad"],
    varieties: [
      {
        id: "erode-turmeric",
        name: "Erode Finger",
        origin: "Erode, Tamil Nadu",
        grade: "Premium Export",
        moisture: "≤ 10%",
        color: "Deep Yellow-Orange",
        packing: ["25 kg PP bags", "50 kg jute bags", "Vacuum packed"],
        minOrder: "50 kg",
        description: "World-renowned Erode turmeric with highest curcumin content. Deep colour, bold fingers, 18–24 month shelf life vacuum packed.",
        specs: [
          { label: "Curcumin Content", value: "3.5–5%" },
          { label: "Moisture", value: "≤ 10%" },
          { label: "Total Ash", value: "≤ 8%" },
          { label: "Volatile Oil", value: "≥ 2.5%" },
          { label: "Form", value: "Whole Finger" },
          { label: "Shelf Life", value: "18–24 months" },
        ],
      },
      {
        id: "salem-turmeric",
        name: "Salem Finger",
        origin: "Salem, Tamil Nadu",
        grade: "A Grade Export",
        moisture: "≤ 10%",
        color: "Bright Yellow",
        packing: ["25 kg PP bags", "50 kg jute bags"],
        minOrder: "50 kg",
        description: "Salem turmeric — bright colour, medium curcumin. Ideal for food colouring and spice blending.",
        specs: [
          { label: "Curcumin Content", value: "2.5–3.5%" },
          { label: "Moisture", value: "≤ 10%" },
          { label: "Form", value: "Whole / Powder" },
        ],
      },
      {
        id: "turmeric-powder",
        name: "Turmeric Powder",
        origin: "Erode / Nizamabad",
        grade: "Steam Sterilised",
        moisture: "≤ 10%",
        color: "Deep Yellow",
        packing: ["100g–25 kg retail & bulk"],
        minOrder: "50 kg",
        description: "Steam-sterilised turmeric powder. FSSAI compliant. Custom mesh sizes available. Private label ready.",
        specs: [
          { label: "Curcumin Content", value: "3–5%" },
          { label: "Moisture", value: "≤ 10%" },
          { label: "Form", value: "Ground powder" },
          { label: "Process", value: "Steam sterilised" },
        ],
      },
    ],
  },
  {
    id: "red-chilli",
    name: "Red Chilli",
    category: "spices",
    emoji: "🌶️",
    hsCode: "HS 0904.21",
    tagline: "Guntur Sannam & Byadagi — ASTA colour 60–200+. GI-tagged.",
    description: "Premium red chillies from Guntur and Byadagi. ASTA colour value 60–200+. Available whole, crushed and powder. GI-tagged varieties. Low moisture, clean & sorted.",
    heroColor: "#C0392B",
    certifications: ["FSSAI", "GI Tagged", "APEDA"],
    originRegions: ["Guntur", "Byadagi", "Warangal"],
    varieties: [
      {
        id: "teja-s17",
        name: "Teja (S17)",
        origin: "Guntur, Andhra Pradesh",
        grade: "Export Grade",
        moisture: "≤ 12%",
        color: "Deep Red",
        packing: ["25 kg PP bags", "10 kg cartons"],
        minOrder: "50 kg",
        description: "India's most exported chilli. High pungency 90,000–1,00,000 SHU. Deep red colour, thin skin.",
        specs: [
          { label: "ASTA Colour", value: "≥ 80" },
          { label: "Scoville Units", value: "90,000–1,00,000" },
          { label: "Moisture", value: "≤ 12%" },
          { label: "Form", value: "Whole / Powder" },
        ],
      },
      {
        id: "byadagi",
        name: "Byadagi",
        origin: "Byadagi, Karnataka",
        grade: "Premium Colour Grade",
        moisture: "≤ 12%",
        color: "Brilliant Red",
        packing: ["25 kg PP bags", "50 kg jute bags"],
        minOrder: "50 kg",
        description: "Prized for colour over heat. Brilliant red pigment, ideal for paprika and colour extracts. GI-tagged variety.",
        specs: [
          { label: "ASTA Colour", value: "≥ 200" },
          { label: "Scoville Units", value: "10,000–15,000" },
          { label: "Moisture", value: "≤ 12%" },
          { label: "Skin Type", value: "Wrinkled" },
        ],
      },
      {
        id: "guntur-sannam",
        name: "Guntur Sannam",
        origin: "Guntur, Andhra Pradesh",
        grade: "ASTA 60+ Export",
        moisture: "≤ 12%",
        color: "Bright Red",
        packing: ["25 kg PP bags", "Bulk"],
        minOrder: "50 kg",
        description: "Balanced heat and colour. ASTA 60–100+. Versatile for food processing and blending.",
        specs: [
          { label: "ASTA Colour", value: "60–100+" },
          { label: "Scoville Units", value: "35,000–50,000" },
          { label: "Moisture", value: "≤ 12%" },
        ],
      },
    ],
  },
  {
    id: "cumin",
    name: "Cumin / Jeera",
    category: "spices",
    emoji: "🟤",
    hsCode: "HS 0909.21",
    tagline: "Rajasthan, MP & Gujarat — Bold & European export grade",
    description: "Premium cumin seeds from Rajasthan, Madhya Pradesh & Gujarat. Bold & European export grade. Singapore-cleaned & machine cleaned. Sortex available.",
    heroColor: "#8B6914",
    certifications: ["FSSAI", "APEDA"],
    originRegions: ["Unjha", "Jodhpur", "Jamnagar"],
    varieties: [
      {
        id: "bold-cumin",
        name: "Bold Grade Cumin",
        origin: "Unjha, Gujarat",
        grade: "Singapore Grade / Bold",
        moisture: "≤ 8%",
        color: "Greenish Brown",
        packing: ["25 kg PP bags", "50 kg jute bags"],
        minOrder: "50 kg",
        description: "Singapore-cleaned bold cumin. Highest export grade from Unjha — world's largest cumin trading market.",
        specs: [
          { label: "Volatile Oil", value: "≥ 2.5%" },
          { label: "Moisture", value: "≤ 8%" },
          { label: "Foreign Matter", value: "≤ 1.5%" },
          { label: "Cleaning", value: "Singapore / Sortex" },
        ],
      },
      {
        id: "european-cumin",
        name: "European Grade Cumin",
        origin: "Rajasthan / MP",
        grade: "European Export",
        moisture: "≤ 7%",
        color: "Olive Green-Brown",
        packing: ["25 kg PP bags"],
        minOrder: "50 kg",
        description: "Machine cleaned to European standards. Ultra-low foreign matter. Preferred by EU spice processors.",
        specs: [
          { label: "Volatile Oil", value: "≥ 2%" },
          { label: "Moisture", value: "≤ 7%" },
          { label: "Foreign Matter", value: "≤ 0.5%" },
        ],
      },
    ],
  },
  {
    id: "coriander",
    name: "Coriander / Dhania",
    category: "spices",
    emoji: "🟢",
    hsCode: "HS 0909.10",
    tagline: "Rajasthan origin — Eagle & Scooter grade, Volatile oil 1.5–2.0%",
    description: "Rajasthan origin coriander in Eagle & Scooter export grades. Whole seeds & powder. Volatile oil 1.5–2.0%. Machine cleaned, low moisture, uniform colour.",
    heroColor: "#1A6B3A",
    certifications: ["FSSAI", "APEDA"],
    originRegions: ["Ramganj Mandi", "Kota", "Rajkot"],
    varieties: [
      {
        id: "eagle-coriander",
        name: "Eagle Grade",
        origin: "Rajasthan",
        grade: "Eagle (Premium Export)",
        moisture: "≤ 9%",
        color: "Olive Green-Brown",
        packing: ["25 kg PP bags", "50 kg jute bags"],
        minOrder: "50 kg",
        description: "Top commercial export grade. Uniform seeds, high volatile oil, preferred by spice processors worldwide.",
        specs: [
          { label: "Volatile Oil", value: "1.5–2.0%" },
          { label: "Moisture", value: "≤ 9%" },
          { label: "Foreign Matter", value: "≤ 1%" },
          { label: "Form", value: "Whole / Powder" },
        ],
      },
      {
        id: "scooter-coriander",
        name: "Scooter Grade",
        origin: "Rajasthan / Gujarat",
        grade: "Scooter (Standard Export)",
        moisture: "≤ 10%",
        color: "Brown-Green",
        packing: ["25 kg PP bags", "Bulk"],
        minOrder: "50 kg",
        description: "Most widely traded coriander grade globally. Good quality, consistent specs, competitive pricing.",
        specs: [
          { label: "Volatile Oil", value: "≥ 0.2%" },
          { label: "Moisture", value: "≤ 10%" },
          { label: "Foreign Matter", value: "≤ 2%" },
        ],
      },
    ],
  },
  {
    id: "black-pepper",
    name: "Black Pepper",
    category: "spices",
    emoji: "⚫",
    hsCode: "HS 0904.11",
    tagline: "Kerala Malabar & Tellicherry — Bulk density 500–600 g/L, ETO-free",
    description: "Kerala origin black pepper from Malabar and Tellicherry. Garbled, semi-garbled and ungarbled. Bold 5–8mm. Bulk density 500–600 g/L. ETO-free available.",
    heroColor: "#2D3748",
    certifications: ["FSSAI", "Spices Board", "ETO-free on request"],
    originRegions: ["Wayanad", "Tellicherry", "Malabar"],
    varieties: [
      {
        id: "malabar-pepper",
        name: "Malabar Garbled",
        origin: "Wayanad, Kerala",
        grade: "FAQ / Garbled",
        moisture: "≤ 12%",
        color: "Black",
        packing: ["25 kg PP bags", "50 kg jute bags"],
        minOrder: "50 kg",
        description: "Classic Malabar pepper. Bold aroma, consistent quality. Garbled & machine cleaned.",
        specs: [
          { label: "Bulk Density", value: "550–600 g/L" },
          { label: "Piperine", value: "≥ 4%" },
          { label: "Moisture", value: "≤ 12%" },
          { label: "Light Berries", value: "≤ 10%" },
          { label: "ETO-free", value: "Available on request" },
        ],
      },
      {
        id: "tellicherry-bold",
        name: "Tellicherry Bold 5mm+",
        origin: "Thalassery, Kerala",
        grade: "TGSEB Premium",
        moisture: "≤ 12%",
        color: "Jet Black",
        packing: ["25 kg PP bags", "Custom"],
        minOrder: "50 kg",
        description: "World's premium pepper. Left to ripen longer — larger berries, deeper aroma, more complex flavour.",
        specs: [
          { label: "Berry Size", value: "5–8 mm bold" },
          { label: "Piperine", value: "≥ 5%" },
          { label: "Bulk Density", value: "500–600 g/L" },
          { label: "Light Berries", value: "≤ 5%" },
        ],
      },
    ],
  },
  {
    id: "cardamom",
    name: "Cardamom",
    category: "spices",
    emoji: "💚",
    hsCode: "HS 0908.31",
    tagline: "Idukki, Kerala — 7–8mm bold, AGEB/AGB/AB/BB grades, Oil 5–8%",
    description: "Idukki, Kerala origin. Green cardamom 7–8mm bold. AGEB, AGB, AB, BB grades. Alleppey & Coorg varieties. Volatile oil 5–8%. Vacuum packed.",
    heroColor: "#1A6B3A",
    certifications: ["FSSAI", "Spices Board"],
    originRegions: ["Idukki", "Alleppey", "Coorg"],
    varieties: [
      {
        id: "cardamom-ageb",
        name: "AGEB Grade 7–8mm",
        origin: "Idukki, Kerala",
        grade: "AGEB (Extra Bold)",
        moisture: "≤ 12%",
        color: "Bright Green",
        packing: ["5 kg vacuum bags", "10 kg cartons", "25 kg PP bags"],
        minOrder: "25 kg",
        description: "Top AGEB grade — extra bold 7–8mm. Brilliant green colour, highest volatile oil content. Premium GCC & EU markets.",
        specs: [
          { label: "Size", value: "7–8 mm bold" },
          { label: "Volatile Oil", value: "6–8%" },
          { label: "Grade", value: "AGEB (Extra Bold)" },
          { label: "Moisture", value: "≤ 12%" },
          { label: "Packing", value: "Vacuum sealed" },
        ],
      },
      {
        id: "cardamom-agb",
        name: "AGB / AB Grade",
        origin: "Kerala / Karnataka",
        grade: "AGB / AB Standard",
        moisture: "≤ 12%",
        color: "Green",
        packing: ["25 kg PP bags", "10 kg cartons"],
        minOrder: "25 kg",
        description: "Standard AGB/AB grade. Good aroma, consistent quality. Widely used in food processing and HoReCa.",
        specs: [
          { label: "Size", value: "6–7 mm" },
          { label: "Volatile Oil", value: "5–6%" },
          { label: "Grades", value: "AGB / AB / BB" },
          { label: "Moisture", value: "≤ 12%" },
        ],
      },
    ],
  },
  {
    id: "whole-spices-blends",
    name: "Whole Spices & Blends",
    category: "spices",
    emoji: "🌿",
    hsCode: "HS 0910.91",
    tagline: "Clove, Cinnamon, Star Anise, Garam Masala, Mace & Fenugreek",
    description: "Premium whole spices and custom blends. Single-origin & blended. ETO-free & steam-sterilised. Halal/Kosher on request. Custom masala formulations available.",
    heroColor: "#6B3A2A",
    certifications: ["FSSAI", "Halal on request", "Kosher on request"],
    originRegions: ["Kerala", "Zanzibar", "Sri Lanka", "Vietnam", "Rajasthan"],
    varieties: [
      {
        id: "clove",
        name: "Clove",
        origin: "Zanzibar & Madagascar",
        grade: "Lalpari / Hand-picked",
        moisture: "≤ 12%",
        color: "Dark Brown",
        packing: ["25 kg PP bags", "Custom retail"],
        minOrder: "50 kg",
        description: "Hand-picked, sun-dried Lalpari grade. Essential oil 15–18%. Stem & whole clove available.",
        specs: [
          { label: "Essential Oil", value: "15–18%" },
          { label: "Moisture", value: "≤ 12%" },
          { label: "Forms", value: "Whole / Stem" },
        ],
      },
      {
        id: "cinnamon",
        name: "Cinnamon",
        origin: "Sri Lanka (Ceylon) & Vietnam",
        grade: "Alba / C4 / C5",
        moisture: "≤ 12%",
        color: "Golden Brown",
        packing: ["25 kg PP bags", "Retail boxes"],
        minOrder: "50 kg",
        description: "Ceylon & Cassia cinnamon. Alba, C4, C5 grades. Quillings, off-cuts & sticks. Oil 0.5–3.5%.",
        specs: [
          { label: "Essential Oil", value: "0.5–3.5%" },
          { label: "Grades", value: "Alba, C4, C5" },
          { label: "Forms", value: "Sticks / Quillings / Powder" },
        ],
      },
      {
        id: "garam-masala",
        name: "Garam Masala",
        origin: "Pan-India blend",
        grade: "Custom / Private Label",
        moisture: "≤ 10%",
        color: "Brown",
        packing: ["100g–25 kg"],
        minOrder: "50 kg",
        description: "Custom blend with 15+ spice base. Private label & white-label ready. Ground, coarse & whole versions. FSSAI certified.",
        specs: [
          { label: "Spice Base", value: "15+ spices" },
          { label: "Forms", value: "Ground / Coarse / Whole" },
          { label: "Custom Recipe", value: "Available" },
          { label: "Min Order", value: "50 kg per blend" },
        ],
      },
    ],
  },
  {
    id: "coffee",
    name: "Coffee",
    category: "commodities",
    emoji: "☕",
    hsCode: "HS 0901.11",
    tagline: "Chikmagalur Arabica & Wayanad Robusta — Green & Roasted",
    description: "Estate-direct coffee from Karnataka and Kerala. CTC & orthodox. AA & AB screen sizes. Specialty grade available. Private label & custom blends.",
    heroColor: "#3D1C00",
    certifications: ["FSSAI", "Organic on request"],
    originRegions: ["Chikmagalur", "Coorg", "Wayanad", "Araku"],
    varieties: [
      {
        id: "arabica",
        name: "Arabica AA/AB",
        origin: "Chikmagalur & Coorg, Karnataka",
        grade: "AA / AB Screen",
        moisture: "≤ 12%",
        color: "Blue-Green",
        packing: ["60 kg jute bags", "Grain-pro bags"],
        minOrder: "100 kg",
        description: "Washed & natural process. Mild fruity-floral profile. Specialty grade available on request.",
        specs: [
          { label: "Screen Size", value: "AA / AB" },
          { label: "Process", value: "Washed / Natural" },
          { label: "Forms", value: "Green / Roasted" },
        ],
      },
      {
        id: "robusta",
        name: "Robusta PB/AB",
        origin: "Wayanad, Kerala & Araku Valley",
        grade: "PB / AB Screen",
        moisture: "≤ 12%",
        color: "Olive Brown",
        packing: ["60 kg jute bags"],
        minOrder: "100 kg",
        description: "High body, low acidity. Ideal for espresso, instant & chicory blends.",
        specs: [
          { label: "Screen Size", value: "PB / AB" },
          { label: "Use", value: "Espresso / Instant" },
          { label: "Forms", value: "Green / Roasted" },
        ],
      },
    ],
  },
  {
    id: "rice",
    name: "Rice",
    category: "commodities",
    emoji: "🌾",
    hsCode: "HS 1006.20",
    tagline: "Basmati 1121, Sona Masoori, Indrayani — 18-month aged, EU-compliant",
    description: "Premium Indian rice varieties. Basmati 1121, Pusa, Sona Masoori, Indrayani. Aged, sortex clean. 18-month aged Basmati. Length 8mm+. EU-compliant.",
    heroColor: "#8B7355",
    certifications: ["APEDA", "FSSAI", "EU compliant"],
    originRegions: ["Punjab", "Haryana", "Andhra Pradesh", "Maharashtra"],
    varieties: [
      {
        id: "basmati-1121",
        name: "Basmati 1121",
        origin: "Punjab / Haryana",
        grade: "Premium Aged Export",
        moisture: "≤ 12%",
        color: "White / Creamy",
        packing: ["1 kg–50 kg bags", "Bulk"],
        minOrder: "1 MT",
        description: "18-month aged Basmati. Extra-long grain 8mm+. Exceptional elongation on cooking up to 20mm. EU-compliant.",
        specs: [
          { label: "Grain Length (raw)", value: "8.3 mm+" },
          { label: "Aged", value: "18 months" },
          { label: "Broken", value: "≤ 1%" },
          { label: "Moisture", value: "≤ 12%" },
        ],
      },
      {
        id: "sona-masoori",
        name: "Sona Masoori",
        origin: "Andhra Pradesh / Karnataka",
        grade: "Sortex Export",
        moisture: "≤ 12%",
        color: "White",
        packing: ["25 kg PP bags", "50 kg bags", "Bulk"],
        minOrder: "1 MT",
        description: "Lightweight aromatic medium-grain. Low starch, popular in Middle East and South Asian diaspora.",
        specs: [
          { label: "Grain Type", value: "Medium grain" },
          { label: "Broken", value: "≤ 5%" },
          { label: "Milling", value: "Double polished" },
        ],
      },
    ],
  },
  {
    id: "pulses-grains",
    name: "Pulses, Beans & Grains",
    category: "commodities",
    emoji: "🫘",
    hsCode: "HS 0713",
    tagline: "Masoor, Moong, Toor Dal, Chickpeas, Millets — AGMARK certified",
    description: "Farm-to-buyer sourcing. AGMARK & FSSAI quality grading. Fumigation & phytosanitary certs. Year-round availability. Bulk vessel loading available.",
    heroColor: "#C4923A",
    certifications: ["AGMARK", "FSSAI", "Phytosanitary"],
    originRegions: ["Rajasthan", "Maharashtra", "MP", "Bihar"],
    varieties: [
      {
        id: "masoor-dal",
        name: "Masoor / Red Lentils",
        origin: "Rajasthan / MP",
        grade: "Sortex / FAQ",
        moisture: "≤ 12%",
        color: "Red-Brown",
        packing: ["25 kg PP bags", "50 kg jute"],
        minOrder: "500 kg",
        description: "Machine cleaned, sortex grade. AGMARK certified. High germination rate.",
        specs: [
          { label: "Types", value: "Whole / Split" },
          { label: "Grade", value: "Sortex / FAQ" },
          { label: "Moisture", value: "≤ 12%" },
        ],
      },
      {
        id: "chickpeas",
        name: "Kabuli Chickpeas",
        origin: "Rajasthan & MP",
        grade: "8–10mm Bold",
        moisture: "≤ 12%",
        color: "Creamy White",
        packing: ["50 kg PP bags", "Bulk"],
        minOrder: "500 kg",
        description: "Bold 8–10mm Kabuli chana. Low aflatoxin. Available whole, split & as besan flour.",
        specs: [
          { label: "Size", value: "8–10 mm bold" },
          { label: "Aflatoxin", value: "Low tested" },
          { label: "Forms", value: "Whole / Split / Besan" },
        ],
      },
    ],
  },
  {
    id: "groundnuts",
    name: "Groundnuts",
    category: "commodities",
    emoji: "🥜",
    hsCode: "HS 1202",
    tagline: "Gujarat Java HPS — Aflatoxin tested, 48–52% oil content",
    description: "Indian groundnuts — high oil content, clean, aflatoxin-tested. Available in multiple grades for food, oil, and confectionery use.",
    heroColor: "#C4923A",
    certifications: ["APEDA", "FSSAI"],
    originRegions: ["Junagadh", "Rajkot", "Saurashtra"],
    varieties: [
      {
        id: "java-hps",
        name: "Java HPS Bold",
        origin: "Saurashtra, Gujarat",
        grade: "HPS (Hand Picked Selected)",
        moisture: "≤ 7%",
        color: "Light Pink-Red",
        packing: ["25 kg PP bags", "50 kg jute bags"],
        minOrder: "500 kg",
        description: "Premium HPS grade. Large kernel, manually sorted, aflatoxin tested. Preferred for blanching and confectionery.",
        specs: [
          { label: "Oil Content", value: "48–52%" },
          { label: "Protein", value: "26–28%" },
          { label: "Aflatoxin", value: "≤ 10 ppb" },
          { label: "Count", value: "40/50, 50/60, 60/70 per 100g" },
        ],
      },
    ],
  },
  {
    id: "sesame-oilseeds",
    name: "Sesame & Oilseeds",
    category: "commodities",
    emoji: "🤍",
    hsCode: "HS 1207.99",
    tagline: "Natural, Hulled, Black & Golden — 99% purity, 50–55% oil",
    description: "Indian sesame seeds with exceptional oil content and purity. Available in natural, hulled, and black varieties. Also mustard, flaxseed and chia.",
    heroColor: "#D4A853",
    certifications: ["APEDA", "FSSAI", "Organic on request"],
    originRegions: ["Gujarat", "Rajasthan", "MP"],
    varieties: [
      {
        id: "natural-sesame-99",
        name: "Natural White 99/1",
        origin: "Gujarat / Rajasthan",
        grade: "99/1 Export Grade",
        moisture: "≤ 6%",
        color: "Creamy White",
        packing: ["25 kg PP bags", "50 kg jute bags"],
        minOrder: "500 kg",
        description: "99% purity benchmark export grade. High oil content. Used in tahini, bread, buns and oil extraction.",
        specs: [
          { label: "Purity", value: "99% minimum" },
          { label: "Oil Content", value: "50–55%" },
          { label: "Moisture", value: "≤ 6%" },
          { label: "FFA", value: "≤ 2%" },
        ],
      },
      {
        id: "black-sesame",
        name: "Black Sesame",
        origin: "Madhya Pradesh",
        grade: "Export Grade",
        moisture: "≤ 6%",
        color: "Jet Black",
        packing: ["25 kg PP bags"],
        minOrder: "200 kg",
        description: "Nutty flavour, health benefits. Popular in Asian cuisines and nutraceutical applications.",
        specs: [
          { label: "Purity", value: "98% minimum" },
          { label: "Oil Content", value: "48–52%" },
          { label: "Moisture", value: "≤ 6%" },
        ],
      },
    ],
  },
  {
    id: "himalayan-salt",
    name: "Himalayan Pink Salt",
    category: "commodities",
    emoji: "🩷",
    hsCode: "HS 2501.00",
    tagline: "100% natural, 84+ trace minerals — Food, Bath, Lamp & Slab grades",
    description: "100% natural Himalayan pink salt. No additives. 84+ trace minerals. Multiple grades: food, bath, lamp, slab. Custom colors. HACCP & ISO documentation.",
    heroColor: "#E8A0A0",
    certifications: ["HACCP", "ISO", "COA"],
    originRegions: ["Khewra", "Punjab Pakistan mines"],
    varieties: [
      {
        id: "food-grade-salt",
        name: "Food Grade Salt",
        origin: "Himalayan mines",
        grade: "Fine / Coarse / X-Coarse",
        moisture: "Dry",
        color: "Pink / White",
        packing: ["Bulk to retail"],
        minOrder: "100 kg",
        description: "Fine, coarse & extra-coarse grinds. 99%+ NaCl. No additives, no anti-caking agents. HACCP & ISO certified.",
        specs: [
          { label: "NaCl Content", value: "99%+" },
          { label: "Trace Minerals", value: "84+" },
          { label: "Grinds", value: "Fine / Coarse / X-Coarse" },
          { label: "Certs", value: "HACCP / ISO" },
        ],
      },
      {
        id: "spa-bath-salt",
        name: "Spa & Bath Grade",
        origin: "Himalayan mines",
        grade: "Coarse Crystals",
        moisture: "Dry",
        color: "Pink / White / Dark Pink",
        packing: ["Custom retail packs"],
        minOrder: "100 kg",
        description: "Therapeutic and cosmetic use. Pink, white & dark pink shades. For bath salts, scrubs and spa kits.",
        specs: [
          { label: "Shades", value: "Pink / White / Dark Pink" },
          { label: "Use", value: "Bath / Spa / Scrubs" },
          { label: "MOQ", value: "100 kg" },
        ],
      },
    ],
  },
  {
    id: "dry-fruits-nuts",
    name: "Dry Fruits & Nuts",
    category: "commodities",
    emoji: "🥜",
    hsCode: "HS 0801.32",
    tagline: "Cashew W180/W240/W320, Raisins, Makhana — Aflatoxin tested",
    description: "Premium cashew kernels, raisins, and makhana. Aflatoxin & SO2 tested. Vacuum/N2-flushed. Multiple grades. GI-tagged. Retail tin, jar & bulk packs.",
    heroColor: "#C4923A",
    certifications: ["FSSAI", "APEDA"],
    originRegions: ["Karnataka", "Kerala", "Goa", "Bihar", "Maharashtra"],
    varieties: [
      {
        id: "cashew-w320",
        name: "Cashew W320",
        origin: "Karnataka / Kerala / Goa",
        grade: "W320 Premium",
        moisture: "≤ 5%",
        color: "Ivory White",
        packing: ["25 lb tins", "Vacuum bags"],
        minOrder: "100 kg",
        description: "320 nuts/lb. Karnataka, Kerala & Goa origin. Vacuum & N2-flushed packing. Aflatoxin <4 ppb.",
        specs: [
          { label: "Count", value: "~320 nuts/lb" },
          { label: "Aflatoxin", value: "< 4 ppb" },
          { label: "Packing", value: "Vacuum / N2-flushed" },
        ],
      },
      {
        id: "cashew-w240",
        name: "Cashew W240",
        origin: "Karnataka / Kerala",
        grade: "W240 Premium",
        moisture: "≤ 5%",
        color: "Uniform Ivory",
        packing: ["25 lb tins", "Retail jars"],
        minOrder: "100 kg",
        description: "Larger 240 nuts/lb premium kernels. Ideal for retail tin packs, gifting & confectionery.",
        specs: [
          { label: "Count", value: "~240 nuts/lb" },
          { label: "Grade", value: "1st Premium" },
          { label: "Use", value: "Retail / Gift / Bakery" },
        ],
      },
      {
        id: "makhana",
        name: "Makhana (Fox Nuts)",
        origin: "Mithila, Bihar",
        grade: "4S–8S Suta",
        moisture: "≤ 8%",
        color: "White",
        packing: ["200g–25 kg"],
        minOrder: "25 kg",
        description: "GI-tagged Mithila Bihar origin. Grades 4S–8S. Low fat, high protein & calcium. 6–12 month shelf life.",
        specs: [
          { label: "Grades", value: "4S / 5S / 6S / 7S / 8S" },
          { label: "GI Tag", value: "Mithila, Bihar" },
          { label: "Shelf Life", value: "6–12 months" },
          { label: "Flavours", value: "Plain / Pudina / Cheese / Custom" },
        ],
      },
    ],
  },
];

export const countries = [
  { name: "United Arab Emirates", region: "Middle East", flag: "🇦🇪" },
  { name: "Saudi Arabia", region: "Middle East", flag: "🇸🇦" },
  { name: "Qatar", region: "Middle East", flag: "🇶🇦" },
  { name: "Kuwait", region: "Middle East", flag: "🇰🇼" },
  { name: "Oman", region: "Middle East", flag: "🇴🇲" },
  { name: "Bahrain", region: "Middle East", flag: "🇧🇭" },
  { name: "United Kingdom", region: "Europe", flag: "🇬🇧" },
  { name: "Netherlands", region: "Europe", flag: "🇳🇱" },
  { name: "Germany", region: "Europe", flag: "🇩🇪" },
  { name: "France", region: "Europe", flag: "🇫🇷" },
  { name: "Spain", region: "Europe", flag: "🇪🇸" },
  { name: "United States", region: "Americas", flag: "🇺🇸" },
  { name: "Canada", region: "Americas", flag: "🇨🇦" },
  { name: "Brazil", region: "Americas", flag: "🇧🇷" },
  { name: "Nigeria", region: "Africa", flag: "🇳🇬" },
  { name: "South Africa", region: "Africa", flag: "🇿🇦" },
  { name: "Kenya", region: "Africa", flag: "🇰🇪" },
  { name: "Ethiopia", region: "Africa", flag: "🇪🇹" },
  { name: "Egypt", region: "Africa", flag: "🇪🇬" },
  { name: "Singapore", region: "Asia Pacific", flag: "🇸🇬" },
  { name: "Malaysia", region: "Asia Pacific", flag: "🇲🇾" },
  { name: "Indonesia", region: "Asia Pacific", flag: "🇮🇩" },
  { name: "Japan", region: "Asia Pacific", flag: "🇯🇵" },
  { name: "Australia", region: "Asia Pacific", flag: "🇦🇺" },
  { name: "Bangladesh", region: "South Asia", flag: "🇧🇩" },
  { name: "Sri Lanka", region: "South Asia", flag: "🇱🇰" },
  { name: "Nepal", region: "South Asia", flag: "🇳🇵" },
  { name: "China", region: "Asia Pacific", flag: "🇨🇳" },
  { name: "Vietnam", region: "Asia Pacific", flag: "🇻🇳" },
];

export const stats = [
  { value: "29+", label: "States Sourced" },
  { value: "50+", label: "Countries Served" },
  { value: "100+", label: "Products" },
  { value: "6", label: "Product Categories" },
];

export const certifications = [
  { name: "FSSAI", fullName: "Food Safety and Standards Authority of India", color: "#1E3A5F" },
  { name: "APEDA", fullName: "Agricultural & Processed Food Products Export Development Authority", color: "#1A6B3A" },
  { name: "Spices Board", fullName: "Spices Board of India — Registered Exporter", color: "#C0392B" },
  { name: "ISO 22000", fullName: "Food Safety Management System Certified", color: "#C4930A" },
];

export const contactInfo = {
  email: ["info@silasya.com", "richa.k@silasya.com", "tarun.k@silasya.com"],
  phone: ["+91 9164626957", "+91 7349498064", "+91 7004514229"],
  whatsapp: "919164626957",
  office: "89, 2nd Floor, Royal Placid Layout, HSR Layout, Bengaluru – 560102",
  warehouse: "27, Parvathi Nagar, Peenya, Bengaluru – 560058",
  website: "www.Shumitra.com",
};

export const originDots = [
  { id: "guntur", name: "Guntur", products: ["Red Chilli"], x: 42, y: 60 },
  { id: "erode", name: "Erode", products: ["Turmeric"], x: 37, y: 72 },
  { id: "wayanad", name: "Wayanad", products: ["Black Pepper", "Cardamom", "Coffee"], x: 33, y: 68 },
  { id: "unjha", name: "Unjha", products: ["Cumin", "Sesame"], x: 22, y: 42 },
  { id: "punjab", name: "Punjab", products: ["Basmati Rice"], x: 30, y: 20 },
  { id: "rajasthan", name: "Rajasthan", products: ["Coriander", "Cumin", "Pulses"], x: 28, y: 35 },
  { id: "chikmagalur", name: "Chikmagalur", products: ["Arabica Coffee"], x: 34, y: 66 },
  { id: "bihar", name: "Bihar", products: ["Makhana"], x: 48, y: 32 },
  { id: "hsr-bengaluru", name: "Bengaluru HQ", products: ["Office & Warehouse"], x: 36, y: 68 },
];
